Feat: SNA-297 deploy contracts to L1 Testnet Sepoilla
Snapchain/cdk-validium-contracts pull request #2
Opened 2023-09-09 05:55 UTC by lesterli

## Summary

* Create a new image to deploy contracts to L1 Testnet Sepoilla

## Test

1. set env vars:
```
      export MNEMONIC="<deployer-mnemonic>"
      export INFURA_PROJECT_ID=<infura-project-id>
      export HARDHAT_NETWORK=sepoilla
```
2. run `npm run deploy:testnet:CDKValidium:sepolia`

**Note**:  The deployer address should be funded with enough Sepolia ETH, and need to change the deployer mnemonic every time testing.

2023-09-09 09:01 UTC, bap2pecs requested changes
I see you set `HARDHAT_NETWORK` in the test plan. where is it used?

Edit: it's in https://github.com/Snapchain/cdk-validium-contracts/blob/main/deployment/2_deployCDKValidiumDeployer.js

2023-09-09 09:01 UTC, bap2pecs commented on package.json
> +    "deploy:CDKValidium:sepolia": "node deployment/1_createGenesis.js && npm run deploy:deployer:CDKValidium:sepolia && npx hardhat run deployment/3_deployContracts.js --network sepolia && npm run sa
can you explain why this is needed? I don't see you running this `deploy:CDKValidium:sepolia` command in the test plan

2023-09-09 09:01 UTC, bap2pecs commented on deployment/testnet/prepareTestnet.js
> +    deployParameters.initialCDKValidiumDeployerOwner = deployer.address;
why do we need this? without it, do you get any errors?

2023-09-09 09:01 UTC, bap2pecs commented on package.json
> +    "saveDeployment:sepolia": "mkdir -p deploymentOutput && cp deployment/deploy_*.json deploymentOutput",
not sure if this change is necessary. can we get the json output from the `deployments/sepolia_$(date +%s)` directory?

or is `$(date +%s)` the tricky part?

2023-09-09 09:01 UTC, bap2pecs commented on docker/Dockerfile.sepolia
> +COPY docker/scripts/deploy_parameters_docker.json deployment/deploy_parameters.json
per https://github.com/Snapchain/cdk-validium-contracts/blob/main/deployment/README.md, it has 

<img width="1083" alt="image" src="https://github.com/Snapchain/cdk-validium-contracts/assets/111917526/4a8939f7-54a8-4e92-ae73-03dc8291d31f">

so it seems we shouldn't COPY from docker/scripts/deploy_parameters_docker.json. I also don't know why it's there.

but I also think we should make `deploy_parameters.json` a user input using a mounted volume instead of build it inside the img

2023-09-09 09:01 UTC, bap2pecs commented on docker/Dockerfile.sepolia
> +CMD ["npm", "run", "deploy:testnet:CDKValidium:sepolia"]
if we remove the line above to only keep `COPY . .`, I feel we can build a general image where user will specify the third argument `"deploy:testnet:CDKValidium:sepolia"`

2023-09-09 09:30 UTC, bap2pecs commented on package.json
> +    "deploy:CDKValidium:sepolia": "node deployment/1_createGenesis.js && npm run deploy:deployer:CDKValidium:sepolia && npx hardhat run deployment/3_deployContracts.js --network sepolia && npm run sa
discussed offline. per https://github.com/Snapchain/cdk-validium-contracts/blob/main/deployment/README.md, we just need to run 2_deployCDKValidiumDeployer before 3_deployContracts.

then we don't need to modify this command

so the steps are:

```
npm run deploy:deployer:CDKValidium:sepolia
npm run deploy:testnet:CDKValidium:sepolia
```

2023-09-09 09:48 UTC, bap2pecs commented on package.json
> +    "saveDeployment:sepolia": "mkdir -p deploymentOutput && cp deployment/deploy_*.json deploymentOutput",
discussed offline. let's expand instead of modifying

2023-09-09 09:51 UTC, bap2pecs commented on deployment/testnet/prepareTestnet.js
> +    deployParameters.initialCDKValidiumDeployerOwner = deployer.address;
discussed offline. this is not needed anymore

2023-09-09 09:53 UTC, bap2pecs commented on docker/Dockerfile.sepolia
> +CMD ["npm", "run", "deploy:testnet:CDKValidium:sepolia"]
discussed offline. we will use `"/bin/sh", "-c"` to create the generic image

2023-09-10 03:08 UTC, bap2pecs requested changes

2023-09-10 03:08 UTC, bap2pecs commented on docker/Dockerfile.sepolia
> +CMD ["/bin/sh"]
since this is a general image, not necessary for Sepolia. let's rename it from `Dockerfile.sepolia` to just `Dockerfile`

2023-09-10 03:08 UTC, bap2pecs commented on docker/scripts/build-sepolia-docker.sh
> +#!/bin/bash
this file should also be renamed to build-docker.sh

2023-09-10 03:08 UTC, bap2pecs commented on docker/docker-compose.yml
I think we should keep this file but rename to `docker-compose.dac-setup`.yml and modify the content to be:

```
services:
  cdk-validium-mock-l1-network:
    container_name: cdk-validium-mock-l1-network
    image: snapchain/geth-cdk-validium-contracts
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - deploy-output:/deploymentOutput
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"

  dac-setup-committee:
    container_name: dac-setup-committee
    image: snapchain/cdk-validium-contracts
    depends_on:
      cdk-validium-mock-l1-network:
        condition: service_started
    volumes:
      - deploy-output:/shared
    environment:
      - JSONRPC_HTTP_URL=http://cdk-validium-mock-l1-network:8545
      - DAC_URL=http://cdk-validium-data-availability:8444
      - DAC_ADDRESS=0x70997970c51812dc3a010c7d01b50e0d17dc79c8
    command:
      - "/bin/sh"
      - "-c"
      - "npm run setup:committee" 

volumes:
  deploy-output:
```

2023-09-10 03:08 UTC, bap2pecs commented on docker/docker-compose.sepolia.yml
> +    image: snapchain/sepolia-cdk-validium-contracts
should be renamed to `snapchain/cdk-validium-contracts`

2023-09-10 03:08 UTC, bap2pecs commented on docker/docker-compose.sepolia.yml
> +      - INFURA_PROJECT_ID=ab12345678b90450c189de3fg77za124
- INFURA_PROJECT_ID=<replace_me>

2023-09-10 03:08 UTC, bap2pecs commented on package.json
> +    "docker:sepolia": "./docker/scripts/build-sepolia-docker.sh",
"docker:build": "./docker/scripts/build-docker.sh",

2023-09-10 03:08 UTC, bap2pecs commented on package.json
> +    "push:docker:sepolia": "docker push snapchain/sepolia-cdk-validium-contracts",
"push:docker": "docker push snapchain/cdk-validium-contracts",

2023-09-10 03:08 UTC, bap2pecs commented on package.json
> +    "push:docker:sepolia:dev": "docker image tag snapchain/sepolia-cdk-validium-contracts snapchain/sepolia-cdk-validium-contracts:dev && docker push snapchain/sepolia-cdk-validium-contracts:dev",
remove `sepolia`

2023-09-10 03:30 UTC, lesterli commented on docker/scripts/build-sepolia-docker.sh
> +sudo docker build -t snapchain/sepolia-cdk-validium-contracts -f docker/Dockerfile.sepolia .
so this need to change `snapchain/sepolia-cdk-validium-contracts` to `snapchain/cdk-validium-contracts`

2023-09-10 07:54 UTC, bap2pecs approved these changes
gogogo!

2023-09-11 01:17 UTC, merged